FROM python:3.9-slim

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements-katoshi.txt .

RUN pip install --no-cache-dir -r requirements-katoshi.txt

COPY strategy_katoshi_fng_ma_buyer.py .

CMD ["python", "-u", "strategy_katoshi_fng_ma_buyer.py"]
